#!/bin/sh /etc/rc.common
# "new(er)" style init script
# Look at /lib/functions/service.sh on a running system for explanations of what other SERVICE_
# options you can use, and when you might want them.
 
START=80
APP=helloserver
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=0
 

start() {

        uci get helloserver 2> /dev/null

        if [[ ! $? == 0 ]]; then
                 uci import helloserver < /dev/null
                 uci add helloserver server
                 uci set helloserver.@server[0].message='Hello'
                 uci commit helloserver                                                              
        fi     

        service_start /usr/bin/$APP
}
 
stop() {
        service_stop /usr/bin/$APP
}

reload() {
        service_stop /usr/bin/$APP
        service_start /usr/bin/$APP
}
